services:
  # fastapi:
  #   build:
  #     context: ./fastapi
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - GRAPHHOPPER_API_KEY=${GRAPHHOPPER_API_KEY}
  #     - LOG_LEVEL=INFO
  #     - LOG_TO_FILE=false
  #     - GRAPH_FILE=philly_bike.graphml
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s

  node:
    build:
      context: ./server
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  react:
    build:
      context: ./client
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

